### ISSUE TITLE
Add metadata to textual-plot

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual-plotext#1]
There's no link on the PyPi page to the Github repo. We should add that to pyproject.toml

We should also update the blog entry to refer to the repo rather than the PyPi page.

Probably explains the low star count on the repo.

**Comment by davep** [comment]
Good catch.

**Comment by davep** [comment]
Metadata updated and version bumped a patch level (didn't seem to make it anything else given it was a metadata tweak).

I'll PR to the blog on the Textual repo in a moment.
