### ISSUE TITLE
Investigate curious plot sizing issues

### ISSUE THREAD

**Issue by davep** [Textualize/textual-plotext#5]
I've just noticed this in passing while working on a personal project, and need to dive into this some more; but it seems that the following things can happen with the sizes of plots:

- Some plots can resize just fine when the app layout changes.
- Some plots won't size past their initial size when the app layout changes.
- Even with a `refresh(layout=True)`, things work to a point then don't seem to work right.
- Even more odd, when all things seem to be working, plots seem to end up with a maximum size and they won't go past that; this smells of a possible issue inside Plotext itself, but that needs to be confirmed.

This is all a bit vague because I'm noting this down before I need to step away from the desk. But the starkest difference can be see if you `make demo` vs `make weather`, and mess about with resizing the terminal with either of them.

Need to investigate and attempt to fix.

I also now wonder why this was originally why I'd designed the widget so that it always needed a subclass with the `plot` method implemented?

Tagging @willmcgugan as requested if there are issues very much worth moving from backlog to TODO (at least for the initial investigation of what might be going on).

**Comment by davep** [comment]
Digging a little deeper and the current hypothesis, based on experimenting: it's looking like the issue is that Plotext will only *fully* take on the values passed to `plt.plotsize` *iff* you perform a `plt.clear_figure`. This means that things like titles, labels, limits, ticks, data, etc.... all get lost and have to be set up again.

As such; this goes back to [the original design I had for this, where everything was driven from `render` and the developer had to subclass the widget and provide a `plot` method](https://github.com/Textualize/textual-plotext/blob/8f4002729c9bda1046f39f73a79a303db13cbd56/src/textual_plotext/plotext_plot.py#L106-L119). At this point I strongly suspect I was right to take that approach.

The current design *does* work, but whereas we dropped the work needed by the dev in subclassing the widget, instead we've added work where they'll need to handle a `Resize` event and ensure that all of their plots get recreated from scratch again.

Sadly it won't be easy to go back to that design without breaking any existing applications using this.

There is a halfway solution that could be taken, where we keep the `plt` properly and the dev can manage things themselves if they wish, but where we also go back to having a method called from `render` that does the right thing and they implement it.

**Comment by davep** [comment]
Digging even further, it looks like this can be fixed with this:

```diff
diff --git a/src/textual_plotext/plotext_plot.py b/src/textual_plotext/plotext_plot.py
index f537798..ad1cdde 100644
--- a/src/textual_plotext/plotext_plot.py
+++ b/src/textual_plotext/plotext_plot.py
@@ -98,7 +98,7 @@ class PlotextPlot(Widget):
         Returns:
             The renderable for displaying the plot.
         """
-        self._plot.plotsize(self.size.width, self.size.height)
+        self._plot._set_size(self.size.width, self.size.height)
         if self.auto_theme:
             self._plot.theme(
                 self.dark_mode_theme if self.app.dark else self.light_mode_theme
```

I have no idea why though. As best as I can make out right now `plot_size` is pretty much a wrapper around `_set_size`; so the effect *should* be the same. And yet this diff seems to make everything work as expected, and so would mean I don't have to go back the the older way of doing things.

**Comment by davidfokkema** [comment]
Just found out that updating textual-plotext fixed my plot not resizing past somewhat larger than the original terminal size. Went searching for this issue to say thanks! 😄
